server:
  port: 8800
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://xxxxxx:3306/aijsq_blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: aijsq_blog
    password: 
  redis:
    host: 139.9.208.63
    port: 6379
    timeout: 3000
    database: 4
    password: cyh123@@@


#==============================knife4j配置==============================
knife4j:
  enable: true
  basic:
    enable: true
    username: test
    password: 123456
  openapi:
    title: AI技术圈接口文档
    description: 一个专注于技术分享的博客平台
    # aaa"
    email: 248954763@qq.com
    concat: AI技术圈
    url: http://www.aijsq.com
    version: v1.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.mojian

#==============================公众号配置==============================
wechat:
  app-id:
  # 公众号AppSecret
  secret:
  # 公众号Token
  token:
  # 公众号AES Key
  aesKey:

  appletAppId:
  appletSecret:

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey:
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
  # 推理接入点ID
  model:

#==============================邮箱配置=======================================
mail:
  smtp:
    host: smtp.163.com
    port: 25
    email:
    password:

#============================第三方登录配置信息===================================
qq:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/mojian/api/auth/callback/qq
weibo:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/mojian/api/auth/weibo

gitee:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/mojian/api/auth/callback/gitee

github:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/shiyi/mojian/api/auth/callback/github
